# Generated by Django 4.0.1 on 2022-02-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restapp',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('phonenumber', models.CharField(max_length=50)),
                ('boot', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50, null=True)),
                ('m_rsrp', models.IntegerField(null=True)),
                ('dl_th', models.IntegerField(null=True)),
                ('ul_th', models.IntegerField(null=True)),
            ],
        ),
    ]
